version: '3.8'

services:
  db_padrones:
    mem_limit: 2g
    image: postgis/postgis:16-3.4
    container_name: db_padrones
    environment:
      - POSTGRES_USER=${POSTGRES_USER_PADRONES}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD_PADRONES}
      - POSTGRES_DB=${POSTGRES_DB_PADRONES}
    ports:
      - "5432:5432"
    volumes:
      - padrones_data:/var/lib/postgresql/data
    restart: unless-stopped

  db_expedientes:
    mem_limit: 1g
    image: postgres:16
    container_name: db_expedientes
    environment:
      - POSTGRES_USER=${POSTGRES_USER_EXPEDIENTES}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD_EXPEDIENTES}
      - POSTGRES_DB=${POSTGRES_DB_EXPEDIENTES}
    ports:
      - "5433:5432"
    volumes:
      - expedientes_data:/var/lib/postgresql/data
    restart: unless-stopped

  api_padrones:
    mem_limit: 1g
    build:
      context: ./sistema_padrones
      dockerfile: Dockerfile
    container_name: api_padrones
    command: sh -c "while ! python manage.py migrate; do echo 'Waiting for DB...'; sleep 2; done; python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./sistema_padrones:/app
    depends_on:
      - db_padrones
    restart: unless-stopped

  api_expedientes:
    mem_limit: 1g
    build:
      context: ./sistema_expedientes
      dockerfile: Dockerfile
    container_name: api_expedientes
    command: sh -c "while ! python manage.py migrate; do echo 'Waiting for DB...'; sleep 2; done; python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8001:8000"
    env_file:
      - .env
    volumes:
      - ./sistema_expedientes:/app
    depends_on:
      - db_expedientes
    restart: unless-stopped

  frontend_portal:
    mem_limit: 1g
    build:
      context: ./portal_profesionales
      dockerfile: Dockerfile
    container_name: frontend_portal
    ports:
      - "5173:5173"
    env_file:
      - .env
    volumes:
      - ./portal_profesionales:/app
      - /app/node_modules
    depends_on:
      - api_padrones
    restart: unless-stopped

volumes:
  padrones_data:
  expedientes_data:
