# Generated by Django 6.0.4 on 2026-04-17 22:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_estadohabilitacion_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='estadohabilitacion',
            options={'verbose_name_plural': 'Estados de Habilitación'},
        ),
        migrations.AlterModelOptions(
            name='profesional',
            options={'verbose_name_plural': 'Profesionales'},
        ),
    ]
