# Generated by Django 6.0.4 on 2026-04-19 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_profesion_historicalprofesion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalprofesional',
            name='observaciones_estado',
            field=models.TextField(blank=True, help_text='Motivo de rechazo, descarte o deshabilitación', null=True),
        ),
        migrations.AddField(
            model_name='profesional',
            name='observaciones_estado',
            field=models.TextField(blank=True, help_text='Motivo de rechazo, descarte o deshabilitación', null=True),
        ),
    ]
