# Generated by Django 6.0.4 on 2026-04-19 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0006_historicalprofesional_observaciones_estado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalprofesional',
            name='direccion',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Dirección / Domicilio'),
        ),
        migrations.AddField(
            model_name='historicalprofesional',
            name='foto_dni_frente',
            field=models.TextField(blank=True, help_text='Foto o PDF', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='historicalprofesional',
            name='foto_dni_reverso',
            field=models.TextField(blank=True, help_text='Foto o PDF', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='historicalprofesional',
            name='razon_social',
            field=models.CharField(blank=True, help_text='Completar si representa a una empresa', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='profesional',
            name='direccion',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Dirección / Domicilio'),
        ),
        migrations.AddField(
            model_name='profesional',
            name='foto_dni_frente',
            field=models.FileField(blank=True, help_text='Foto o PDF', null=True, upload_to='documentos/dni/'),
        ),
        migrations.AddField(
            model_name='profesional',
            name='foto_dni_reverso',
            field=models.FileField(blank=True, help_text='Foto o PDF', null=True, upload_to='documentos/dni/'),
        ),
        migrations.AddField(
            model_name='profesional',
            name='razon_social',
            field=models.CharField(blank=True, help_text='Completar si representa a una empresa', max_length=150, null=True),
        ),
    ]
