# Generated by Django 6.0.4 on 2026-04-19 16:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0007_historicalprofesional_direccion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalprofesional',
            name='foto_dni_frente',
            field=models.TextField(blank=True, help_text='Foto o PDF', max_length=100, null=True, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'pdf'])]),
        ),
        migrations.AlterField(
            model_name='historicalprofesional',
            name='foto_dni_reverso',
            field=models.TextField(blank=True, help_text='Foto o PDF', max_length=100, null=True, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'pdf'])]),
        ),
        migrations.AlterField(
            model_name='profesional',
            name='foto_dni_frente',
            field=models.FileField(blank=True, help_text='Foto o PDF', null=True, upload_to='documentos/dni/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'pdf'])]),
        ),
        migrations.AlterField(
            model_name='profesional',
            name='foto_dni_reverso',
            field=models.FileField(blank=True, help_text='Foto o PDF', null=True, upload_to='documentos/dni/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'pdf'])]),
        ),
    ]
