# Generated by Django 6.0.4 on 2026-04-19 17:06

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0008_alter_historicalprofesional_foto_dni_frente_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionPortal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_portal', models.URLField(default='https://portal.ejemplo.com', help_text='$URL_PORTAL')),
                ('nombre_organismo', models.CharField(default='Intendencia de Ejemplo', help_text='$NOMBRE_ORGANISMO', max_length=200)),
                ('sinonimo_sitio', models.CharField(default='El Portal', help_text='$SINONIMO_SITIO', max_length=200)),
                ('direccion_organismo', models.CharField(default='Calle Falsa 123', help_text='$DIRECCION_ORGANISMO', max_length=255)),
                ('mail_organismo', models.EmailField(default='contacto@ejemplo.com', help_text='$MAIL_ORGANISMO', max_length=254)),
                ('texto_terminos_markdown', models.TextField(blank=True, help_text='Contenido base con variables (ej. $NOMBRE_ORGANISMO)', null=True)),
            ],
            options={
                'verbose_name_plural': 'Configuraciones del Portal',
            },
        ),
        migrations.CreateModel(
            name='HistoricalConfiguracionPortal',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('url_portal', models.URLField(default='https://portal.ejemplo.com', help_text='$URL_PORTAL')),
                ('nombre_organismo', models.CharField(default='Intendencia de Ejemplo', help_text='$NOMBRE_ORGANISMO', max_length=200)),
                ('sinonimo_sitio', models.CharField(default='El Portal', help_text='$SINONIMO_SITIO', max_length=200)),
                ('direccion_organismo', models.CharField(default='Calle Falsa 123', help_text='$DIRECCION_ORGANISMO', max_length=255)),
                ('mail_organismo', models.EmailField(default='contacto@ejemplo.com', help_text='$MAIL_ORGANISMO', max_length=254)),
                ('texto_terminos_markdown', models.TextField(blank=True, help_text='Contenido base con variables (ej. $NOMBRE_ORGANISMO)', null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical configuracion portal',
                'verbose_name_plural': 'historical Configuraciones del Portal',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
