# Generated by Django 6.0.4 on 2026-04-17 22:09

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Padron',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_padron', models.CharField(max_length=50, unique=True)),
                ('geometria', django.contrib.gis.db.models.fields.PolygonField(blank=True, null=True, srid=4326)),
                ('departamento', models.CharField(max_length=100)),
                ('localidad', models.CharField(max_length=100)),
                ('barrio', models.CharField(blank=True, max_length=100, null=True)),
                ('direccion_fisica', models.CharField(blank=True, max_length=255, null=True)),
                ('tipo_suelo', models.CharField(choices=[('URBANO', 'Urbano'), ('SUBURBANO', 'Suburbano'), ('RURAL', 'Rural')], default='URBANO', max_length=20)),
                ('area_metros_cuadrados', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('valor_catastral', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('fecha_ultima_actualizacion', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Solicitud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_tramite', models.CharField(max_length=150)),
                ('descripcion_detallada', models.TextField(blank=True, null=True)),
                ('estado_solicitud', models.CharField(choices=[('BORRADOR', 'Borrador'), ('PENDIENTE_ENVIO', 'Pendiente de Envío'), ('ENVIADA', 'Enviada al Sistema de Expedientes'), ('ACEPTADA', 'Aceptada (Expediente Creado)'), ('RECHAZADA_MESA', 'Rechazada por Mesa de Entrada')], default='BORRADOR', max_length=20)),
                ('observaciones_rechazo', models.TextField(blank=True, help_text='Razón del rechazo si el Sistema B no acepta el trámite', null=True)),
                ('numero_expediente_generado', models.CharField(blank=True, help_text='Referencia al Sistema B', max_length=50, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_ultima_modificacion', models.DateTimeField(auto_now=True)),
                ('fecha_envio_sistema_b', models.DateTimeField(blank=True, null=True)),
                ('padron', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='solicitudes', to='territorio.padron')),
                ('profesional', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='solicitudes', to='usuarios.profesional')),
            ],
        ),
    ]
