# Generated by Django 6.0.4 on 2026-04-17 22:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('territorio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoSolicitud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TipoPadron',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TipoSuelo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TipoTramite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='estado_solicitud',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='territorio.estadosolicitud'),
        ),
        migrations.AddField(
            model_name='padron',
            name='tipo_padron',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='territorio.tipopadron'),
        ),
        migrations.AlterField(
            model_name='padron',
            name='tipo_suelo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='territorio.tiposuelo'),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='tipo_tramite',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='territorio.tipotramite'),
        ),
    ]
