# Generated by Django 6.0.4 on 2026-04-17 22:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('territorio', '0002_estadosolicitud_tipopadron_tiposuelo_tipotramite_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='padron',
            name='tipo_suelo',
        ),
        migrations.DeleteModel(
            name='TipoSuelo',
        ),
    ]
