# Generated by Django 6.0.4 on 2026-04-17 22:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('territorio', '0003_remove_padron_tipo_suelo_delete_tiposuelo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='estadosolicitud',
            options={'verbose_name_plural': 'Estados de Solicitud'},
        ),
        migrations.AlterModelOptions(
            name='padron',
            options={'verbose_name_plural': 'Padrones'},
        ),
        migrations.AlterModelOptions(
            name='solicitud',
            options={'verbose_name_plural': 'Solicitudes'},
        ),
        migrations.AlterModelOptions(
            name='tipopadron',
            options={'verbose_name_plural': 'Tipos de Padrón'},
        ),
        migrations.AlterModelOptions(
            name='tipotramite',
            options={'verbose_name_plural': 'Tipos de Trámite'},
        ),
    ]
