# Generated by Django 6.0.4 on 2026-04-18 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('territorio', '0005_historicalestadosolicitud_historicalpadron_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpadron',
            name='atributos_gis',
            field=models.JSONField(blank=True, help_text='Propiedades originales del GeoJSON', null=True),
        ),
        migrations.AddField(
            model_name='padron',
            name='atributos_gis',
            field=models.JSONField(blank=True, help_text='Propiedades originales del GeoJSON', null=True),
        ),
    ]
