# Generated by Django 6.0.4 on 2026-04-18 03:48

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('territorio', '0006_historicalpadron_atributos_gis_padron_atributos_gis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalpadron',
            name='geometria',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=4326),
        ),
        migrations.AlterField(
            model_name='padron',
            name='geometria',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=4326),
        ),
    ]
