# Generated by Django 6.0.4 on 2026-04-18 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('territorio', '0007_alter_historicalpadron_geometria_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalpadron',
            name='numero_padron',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='padron',
            name='numero_padron',
            field=models.CharField(max_length=50),
        ),
    ]
