# Generated by Django 6.0.4 on 2026-04-18 17:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('territorio', '0008_alter_historicalpadron_numero_padron_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalsolicitud',
            name='padron',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='territorio.padron', verbose_name='ID Padrón'),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='padron',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='solicitudes', to='territorio.padron', verbose_name='ID Padrón'),
        ),
    ]
