# Generated by Django 6.0.4 on 2026-04-19 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('territorio', '0009_alter_historicalsolicitud_padron_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='estadosolicitud',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalestadosolicitud',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
    ]
