# Generated by Django 6.0.4 on 2026-04-19 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('territorio', '0010_estadosolicitud_descripcion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionSolicitud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extensiones_permitidas', models.CharField(default='.pdf,.zip,.rar', help_text='Separadas por coma (ej: .pdf,.zip)', max_length=255)),
                ('tamano_maximo_archivo_mb', models.DecimalField(decimal_places=2, default=10.0, help_text='Tamaño máximo por archivo en MB', max_digits=5)),
                ('tamano_maximo_total_mb', models.DecimalField(decimal_places=2, default=50.0, help_text='Suma total máxima de archivos por solicitud en MB', max_digits=5)),
            ],
            options={
                'verbose_name': 'Parámetros de Solicitudes',
                'verbose_name_plural': 'Configuraciones de Solicitudes',
            },
        ),
    ]
