# Generated by Django 6.0.4 on 2026-04-19 23:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('territorio', '0011_configuracionsolicitud'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchivoTecnico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to='archivos_tecnicos/%Y/%m/')),
                ('nombre_original', models.CharField(max_length=255)),
                ('tamano_bytes', models.BigIntegerField()),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('solicitud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archivos', to='territorio.solicitud')),
            ],
        ),
    ]
