# Generated by Django 6.0.4 on 2026-04-17 03:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Expediente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_expediente', models.CharField(max_length=50, unique=True)),
                ('padron_referencia', models.CharField(help_text='ID o número de padrón del Sistema GIS', max_length=50)),
                ('solicitante_referencia', models.CharField(help_text='DNI o Matrícula del Profesional', max_length=100)),
                ('asunto_principal', models.CharField(max_length=255)),
                ('tipo_tramite', models.CharField(max_length=150)),
                ('prioridad', models.CharField(choices=[('BAJA', 'Baja'), ('NORMAL', 'Normal'), ('ALTA', 'Alta'), ('URGENTE', 'Urgente')], default='NORMAL', max_length=20)),
                ('cantidad_fojas', models.PositiveIntegerField(default=1)),
                ('estado_actual', models.CharField(choices=[('INICIADO', 'Iniciado en Mesa de Entrada'), ('EN_REVISION', 'En Revisión Técnica'), ('OBSERVADO', 'Observado / Requiere cambios'), ('RESUELTO', 'Resuelto / Aprobado'), ('ARCHIVADO', 'Archivado')], default='INICIADO', max_length=20)),
                ('fecha_caratulado', models.DateTimeField(auto_now_add=True)),
                ('fecha_cierre', models.DateTimeField(blank=True, null=True)),
                ('fecha_vencimiento_plazo', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Oficina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_oficina', models.CharField(max_length=150, unique=True)),
                ('codigo_oficina', models.CharField(max_length=20, unique=True)),
                ('es_activa', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='DocumentoAdjunto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo_adjunto', models.FileField(upload_to='documentos_expedientes/%Y/%m/')),
                ('nombre_documento', models.CharField(max_length=255)),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('usuario_que_subio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('expediente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='gestion_expedientes.expediente')),
            ],
        ),
        migrations.CreateModel(
            name='Movimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_movimiento', models.CharField(choices=[('PASE', 'Pase de Oficina'), ('AGREGADO_DOCS', 'Agregado de Documentos'), ('INTERVENCION', 'Intervención Técnica')], default='PASE', max_length=20)),
                ('fojas_agregadas', models.PositiveIntegerField(default=0)),
                ('observaciones_del_pase', models.TextField(blank=True, null=True)),
                ('fecha_envio', models.DateTimeField(auto_now_add=True)),
                ('fecha_recepcion', models.DateTimeField(blank=True, null=True)),
                ('expediente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='gestion_expedientes.expediente')),
                ('usuario_que_envia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pases_enviados', to=settings.AUTH_USER_MODEL)),
                ('usuario_que_recibe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pases_recibidos', to=settings.AUTH_USER_MODEL)),
                ('oficina_destino', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_destino', to='gestion_expedientes.oficina')),
                ('oficina_origen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_origen', to='gestion_expedientes.oficina')),
            ],
        ),
        migrations.AddField(
            model_name='expediente',
            name='oficina_actual',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expedientes_actuales', to='gestion_expedientes.oficina'),
        ),
    ]
