# Generated by Django 6.0.4 on 2026-04-17 22:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_expedientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoExpediente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='PrioridadExpediente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TipoMovimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TipoTramiteExpediente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='expediente',
            name='estado_actual',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='gestion_expedientes.estadoexpediente'),
        ),
        migrations.AlterField(
            model_name='expediente',
            name='prioridad',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='gestion_expedientes.prioridadexpediente'),
        ),
        migrations.AlterField(
            model_name='movimiento',
            name='tipo_movimiento',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='gestion_expedientes.tipomovimiento'),
        ),
        migrations.AlterField(
            model_name='expediente',
            name='tipo_tramite',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='gestion_expedientes.tipotramiteexpediente'),
        ),
    ]
