# Generated by Django 6.0.4 on 2026-04-17 22:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_expedientes', '0002_estadoexpediente_prioridadexpediente_tipomovimiento_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='documentoadjunto',
            options={'verbose_name_plural': 'Documentos Adjuntos'},
        ),
        migrations.AlterModelOptions(
            name='estadoexpediente',
            options={'verbose_name_plural': 'Estados de Expediente'},
        ),
        migrations.AlterModelOptions(
            name='expediente',
            options={'verbose_name_plural': 'Expedientes'},
        ),
        migrations.AlterModelOptions(
            name='movimiento',
            options={'verbose_name_plural': 'Movimientos'},
        ),
        migrations.AlterModelOptions(
            name='oficina',
            options={'verbose_name_plural': 'Oficinas'},
        ),
        migrations.AlterModelOptions(
            name='prioridadexpediente',
            options={'verbose_name_plural': 'Prioridades de Expediente'},
        ),
        migrations.AlterModelOptions(
            name='tipomovimiento',
            options={'verbose_name_plural': 'Tipos de Movimiento'},
        ),
        migrations.AlterModelOptions(
            name='tipotramiteexpediente',
            options={'verbose_name_plural': 'Tipos de Trámite de Expediente'},
        ),
    ]
